// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuwkzferusgzzfcnrkgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51d2t6ZmVydXNnenpmY25ya2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTMzNzEsImV4cCI6MjA2MTY2OTM3MX0.VqMglizHJHDW_FVlhThjTRnke7rBn4VaSi_M42RSC5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);